name: Setup Fastreleaser
description: Download and install fastreleaser v1.0.0, verify version

inputs:
  github-token:
    description: 'GitHub token with read access to localcompose/fastreleaser (default: GITHUB_TOKEN)'
    default: ${{ github.token }}
    required: false

runs:
  using: composite
  steps:
    - name: Download fastreleaser v1.0.0
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        curl -H "Authorization: Bearer $GH_TOKEN" \
             -L -o fastreleaser.tar.gz \
             https://github.com/localcompose/fastreleaser/releases/download/v1.0.0/fastreleaser_Linux_x86_64.tar.gz
        tar -xzf fastreleaser.tar.gz
        sudo mv fastreleaser /usr/local/bin/

    - name: Check fastreleaser version
      shell: bash
      run: fastreleaser -v || fastreleaser
